let conc1 = "Macaco ";
let conc2 = "No Navio";
let concatenar = conc1.concat(conc2);
console.log(concatenar);

let Max = Math.max(20);
console.log(Max);

let Min = Math.min(2);
console.log(Min);

let Add = Min + Max;
console.log(Add);

let Sub = Min - Max;
console.log(Sub);

let Dividir = Min / Max;
console.log(Dividir);

let Mult = Min * Max;
console.log(Mult);

let expoente = Math.pow(30,3);
console.log(expoente);
