let Conc1 = "Macaco ";
let Conc2 = "No Navio";
let Concatenar = Conc1.concat(Conc2);
console.log(Concatenar);

let Max = Math.max(20);
console.log(Max);

let Min = Math.min(2);
console.log(Min);

let Add = Min + Max;
console.log(Add);

let Sub = Min - Max;
console.log(Sub);

let Dividir = Min / Max;
console.log(Dividir);

let Mult = Min * Max;
console.log(Mult);

let expoente = Math.pow(30,3);
console.log(expoente);
