let texto1 = "Macaco ";
let texto2 = "No Navio";
let resultado = texto1.concat(texto2);
console.log(resultado);

let Max = Math.max(20);
console.log(Max);

let Min = Math.min(2);
console.log(Min);

let Add = Min + Max;
console.log(Add);

let Sub = Min - Max;
console.log(Sub);

let Dividir = Min / Max;
console.log(Dividir);

let Mult = Min * Max;
console.log(Mult);

let expoente = Math.pow(30,3);
console.log(expoente);